### PR TITLE
feat: introduce `@stylistic/eslint-plugin-plus`

### PR DESCRIPTION
**Pull request by antfu**
#136

### CODE REVIEW

**Comment by ljharb** [comment]
Why "plus"?

**Comment by antfu** [comment]
Any name suggestions?

**Comment by antfu** [comment]
A few in my mind:

- `extra` - I guess it's ok, but it feels a bit "excessive" to me.
- `additional` - I personally feel it's a bit too long.
- `more` - "JavaScript Rules, TypeScript Rules, More Rules" feels a bit weird
- `plus` - Short, with the meaning of `additional` but not as "excessive" as `extra`


In that regard, I am not a native speaker so my feeling could be inaccurate. Open for suggestions

**Comment by antfu** [comment]
I am merging this to `dev` branch for now so we can start work on rules. Still open for better naming until it get published in the next minor

**Comment by ljharb** [comment]
I’m a bit confused why it needs to be a separate plugin tbh. If it doesn’t belong in the main plugin, why is it in stylistic at all?

**Comment by antfu** [comment]
I explained the reason in https://github.com/eslint-stylistic/eslint-stylistic/issues/136

For users who directly use `@stylistic/eslint-plugin`, it's not a concern. And eventually, we will merge all rules into a single plugin, but that would be a breaking change in the future.

**Comment by ljharb** [comment]
Adding rules is semver-minor; it's only adding enabled things to a config that'd be a breaking change.

I don't find that reason compelling tbh; it just kind of seems like you're trying to move your personal rules under this quasi-official branding :-/

**Comment by antfu** [comment]
> you're trying to move your personal rules under this quasi-official branding :-/

I found that offensive if you say so. I spend a lot of effort on migrating and maintaining this because I care. I tried hard to keep things natural, and only proposed to add rules that improve whitespace and solves long-standing issue that no one was going to fix. I don't know how I can help communicate this better. You ignore the technical reasoning and accuse me like that out of nowhere.

**Comment by ljharb** [comment]
I don't mean to make an accusation, but you're making a ton of unilateral changes without many others weighing in.

**Pull request merged**
