### PR TITLE
refactor(js): migrate quote-props to ts

### PR DESCRIPTION
**Pull request by alexzhang1030**
Part of #70

### CODE REVIEW

**Comment by alexzhang1030** [comment]
Aha, it's a type issue of `typescript-eslint` library.

**Comment by antfu** [comment]
What issue you are referring to?

**Comment by alexzhang1030** [comment]
It's about the type check.

image

The imported type `ValidTestCase` from `@types/eslint` does not satisfy the test case, type check failed.

**Comment by antfu** [comment]
You can change the `env` to `parserOptions: { ecmaVersion: 6 }`

**Comment by alexzhang1030** [comment]
> You can change the `env` to `parserOptions: { ecmaVersion: 6 }`

Great, I was think about it before, but I'm not sure these two are the same or different.

**Review by antfu — APPROVED** [review]

**Pull request merged**
