### PR TITLE
feat: rename `func-call-spacing` to `function-call-spacing`, provide back alias

### LINKED ISSUE #39: Rename func-call-spacing to function-call-spacing
## Overview

Moving from Discord, I propose renaming of rule `func-call-spacing` to `function-call-spacing` for the following reasons:

1. Inconsistent naming scheme based on the following function-related rule name:
  a. `function-call-argument-newline`
  b. `function-paren-newline`
2. Clearer and more concise rule name. This rule is referring to functions and not to be confused with similar-sounding terms like func*tor*

### PR DESCRIPTION
**Pull request by Namchee**
## Overview

Closes #39 

This pull request adds a new alias of `func-call-spacing` named `function-call-spacing` which doesn't change the rule behavior at all.

This pull request takes a different approach from #40. Instead of renaming the rule that potentially breaks existing rule setup, it adds a new alias to the same rule.

### CODE REVIEW

**Comment by antfu** [comment]
Did you do that manually? Many files are auto-generated. It's better to maintain an alias list in `scripts/prepare.ts` and update the script to generate them automatically.

**Comment by Namchee** [comment]
@antfu, regrettably yes, since I haven't read the scripts carefully. I've added aliasing logic in the preparation script.

**Comment by Namchee** [comment]
Looks like the `prepare` script is changed, will update soon

**Review by antfu — APPROVED** [review]
Well done. Thanks for the high-quality PR 👍

**Pull request merged**
