### PR TITLE
feat(indent): support for JSXText indentation

### PR DESCRIPTION
**Pull request by Daydreamer-riri**
### Description

For specific discussions, see #378.

- Support JSXText indentation for the indent rule.
- ‌‌‌‌‌‌Make the `indent` rule pass all tests of `jsx-indent`.

### Linked Issues

#378

### CODE REVIEW

**Comment by hyoban** [comment]
Can we change the shared configurations now? Don't ignore jsx-related nodes and remove `jsx-indent` rule.

https://github.com/eslint-stylistic/eslint-stylistic/blob/c11f1d6f26c13b29fd44c95c908922cb79a0ac82/packages/eslint-plugin/configs/customize.ts#L115-L154

https://github.com/eslint-stylistic/eslint-stylistic/blob/c11f1d6f26c13b29fd44c95c908922cb79a0ac82/packages/eslint-plugin/configs/customize.ts#L238

**Comment by Daydreamer-riri** [comment]
> Can we change the shared configurations now? Don't ignore jsx-related nodes and remove `jsx-indent` rule.

Sure, I will commit as soon as possible.

**Comment by hyoban** [comment]
Or maybe change the configurations in a separate PR?

**Comment by Daydreamer-riri** [comment]
‌‌That's a good idea. I will submit a PR to change the configuration after this PR is merged.

**Comment by hyoban** [comment]
FYI. It seems we can not just remove `JSXOpeningElement` and `JSXClosingElement`, which will produce a wrong indent for `TSTypeParameterInstantiation`.

I need to set different options for js and jsx files. Js files should add them to `ignoredNodes` and jsx files shouldn't.

**Comment by antfu** [comment]
So, does this mean we could deprecate `jsx-indent` then? I think it worth to have a option to opt-out the JSX handing as well

**Comment by Daydreamer-riri** [comment]
> So, does this mean we could deprecate `jsx-indent` then? I think it's worth to have an option to opt-out the JSX handling as well

Currently, `indent` has passed all the `jsx-indent` tests (these tests have been reasonably modified), and I think `jsx-indent` can be deprecated. If there are any issues in the future, I will take responsibility for handling them.

**Review by antfu — APPROVED** [review]

**Pull request merged**
