### PR TITLE
fix(indent): correct indentation in chained methods calls with generics

### LINKED ISSUE #270: `indent`: bad indentation in chained methods calls with generics
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

when chaining methods, if one of the method contains generics, the indentation computing fails
In below case it is the reducer function: its callback ask indentation of 2 instead of indentation of 4

```
const map: Record<string, string> = {};

const map2 = Object.keys(map)
  .filter((key) => true)
  .reduce<Record<string, string>>((result, key) => {
    result[key] = map[key];
    return result;
  }, {});
```

```
  6:1  error  Expected indentation of 2 spaces but found 4  @stylistic/indent
  7:1  error  Expected indentation of 2 spaces but found 4  @stylistic/indent
  8:1  error  Expected indentation of 0 spaces but found 2  @stylistic/indent

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
```

### Reproduction

https://stackblitz.com/edit/github-caheqy?file=src%2Findex.ts

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

### PR DESCRIPTION
**Pull request by 9romise**
### Linked Issues

Closes #270

### CODE REVIEW

**Review by antfu — APPROVED** [review]

**Comment by paztis** [comment]
Problem is partially resolve but other cases appears

I update my sample: https://stackblitz.com/edit/github-caheqy-gwabam?file=src%2Findex.ts

We still have an error: it only works for the top level items.
Inside a class for example we have the indentation bad lint

**Comment by 9romise** [comment]
> Problem is partially resolve but other cases appears
> 
> I update my sample: https://stackblitz.com/edit/github-caheqy-gwabam?file=src%2Findex.ts
> 
> We still have an error: it only works for the top level items.
> Inside a class for example we have the indentation bad lint
> 

Thanks for your reply, I will fix it soon.

**Comment by 9romise** [comment]
> Problem is partially resolve but other cases appears
> 
> I update my sample: https://stackblitz.com/edit/github-caheqy-gwabam?file=src%2Findex.ts
> 
> We still have an error: it only works for the top level items. Inside a class for example we have the indentation bad lint

Hello, sorry for reply latly.
当然，以下是这段话的英文翻译：

---

I carefully reviewed the cases you provided and found that they don't seem to be errors. If the type declarations of the methods are removed, it looks like this:
``` javascript
categorySelector
    = createSelector(
      this.sliceSelector.bind(this),
      (slice) => slice.category
    );
```
The `CallExpression` of the function is at the same indentation level as the `=`.

Btw, we can create a new issue so that more people can join the discussion.

**Comment by 9romise** [comment]
> Problem is partially resolve but other cases appears
> 
> I update my sample: https://stackblitz.com/edit/github-caheqy-gwabam?file=src%2Findex.ts
> 
> We still have an error: it only works for the top level items. Inside a class for example we have the indentation bad lint


I carefully reviewed the cases you provided and found that they don't seem to be errors. If the type declarations of the methods are removed, it looks like this:
``` javascript
categorySelector
    = createSelector(
      this.sliceSelector.bind(this),
      (slice) => slice.category
    );
```
The `CallExpression` of the function is at the same indentation level as the `=`.

Btw, we can create a new issue so that more people can join the discussion.

**Pull request merged**
